#!/bin/bash

echo "🤖 Setting up Personal Chatbot with Together AI"
echo "=============================================="
echo ""
echo "To set up your personal chatbot, follow these steps:"
echo ""
echo "1. 🌐 Visit https://api.together.xyz/"
echo "2. 📝 Sign up for a free account"
echo "3. 🔑 Get your API key from the dashboard"
echo "4. 📁 Edit the .env file in your project root"
echo "5. 🔄 Replace 'your_together_ai_api_key_here' with your actual API key"
echo ""
echo "The chatbot uses the Llama-3.2-3B-Instruct-Turbo model which is:"
echo "✅ Free to use with Together AI"
echo "✅ Fast and efficient"
echo "✅ Great for conversational AI"
echo ""
echo "Your chatbot will:"
echo "🎯 Answer questions about your background, skills, and projects"
echo "💬 Provide a conversational interface for visitors"
echo "📱 Work on both desktop and mobile"
echo "🌙 Support light and dark modes"
echo ""
echo "After setting up your API key, run 'npm run dev' to test the chatbot!"
